### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kometchtech** [shawn1m/overture#118]
When the forwarded DNS does not return a reply for some reason, it seems to be `SIGSEGV` 
in the case of i/o timeout as follows.

```
INFO[0000] Overture v1.5-rc1                            
INFO[0000] If you need any help, please visit the project repository: https://github.com/shawn1m/overture 
INFO[0000] Load domain /etc/overture/domain_primary successful with 1 records  
WARN[0000] There is no element in domain whitelist file 
INFO[0000] Load /etc/overture/ip_network_primary successful 
WARN[0000] There is no element in /etc/overture/ip_network_alternative 
INFO[0000] Minimum TTL is disabled                      
INFO[0000] CacheSize is 102400                          
INFO[0000] Load hosts file successful                   
INFO[0000] Start overture on :53                        
WARN[0002] pdns_rec Fail: read udp 172.17.0.2:45224->192.168.122.223:9853: i/o timeout 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1867a8]

goroutine 19 [running]:
github.com/miekg/dns.(*Msg).PackBuffer(0x0, 0x0, 0x0, 0x0, 0x0, 0x1ef0ac, 0x442000f1d0, 0x442014c060, 0x13)
        /home/travis/gopath/src/github.com/miekg/dns/msg.go:757 +0x18
github.com/miekg/dns.(*Msg).Pack(0x0, 0x442014c060, 0x13, 0x1f0610, 0x4420124150, 0x442000a400)
        /home/travis/gopath/src/github.com/miekg/dns/msg.go:750 +0x2c
github.com/miekg/dns.(*response).WriteMsg(0x44200ee280, 0x0, 0x1, 0x4420122050)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:770 +0x34
github.com/shawn1m/overture/core/inbound.(*Server).ServeDNS(0x44200866c0, 0x2b5160, 0x44200ee280, 0x442010a360)
        /home/travis/gopath/src/github.com/shawn1m/overture/core/inbound/server.go:65 +0x1e0
github.com/miekg/dns.(*ServeMux).ServeDNS(0x442000a640, 0x2b5160, 0x44200ee280, 0x442010a360)
        /home/travis/gopath/src/github.com/miekg/dns/serve_mux.go:128 +0x54
github.com/miekg/dns.(*Server).serveDNS(0x44200cc000, 0x44200ee280)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:688 +0x260
github.com/miekg/dns.(*Server).serve(0x44200cc000, 0x44200ee280)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:573 +0x274
github.com/miekg/dns.(*Server).worker(0x44200cc000, 0x44200ee100)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:269 +0x180
created by github.com/miekg/dns.(*Server).spawnWorker
        /home/travis/gopath/src/github.com/miekg/dns/server.go:284 +0x6c
```

**Comment by myl107** [comment]
There is the same problem on Raspberry Pi 3B+ (armv7l, Raspbian based on Debian Stretch).

**Comment by shawn1m** [comment]
Catch this error now, try v1.5-rc2.

**Comment by kiolygenius** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c11e6]

goroutine 8 [running]:
github.com/miekg/dns.(*Msg).PackBuffer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002c4a00, 0x1a, 0xc00003fc18)
        /home/travis/gopath/src/github.com/miekg/dns/msg.go:757 +0x26
github.com/miekg/dns.(*Msg).Pack(0x0, 0x1, 0x4, 0xc000290ec0, 0xf, 0x0)
        /home/travis/gopath/src/github.com/miekg/dns/msg.go:750 +0x3c
github.com/miekg/dns.(*response).WriteMsg(0xc00027eb00, 0x0, 0x1, 0xc000281eb0)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:770 +0x4d
github.com/shawn1m/overture/core/inbound.(*Server).ServeDNS(0xc000084120, 0x703140, 0xc00027eb00, 0xc000277320)
        /home/travis/gopath/src/github.com/shawn1m/overture/core/inbound/server.go:65 +0x268
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc00000a6e0, 0x703140, 0xc00027eb00, 0xc000277320)
        /home/travis/gopath/src/github.com/miekg/dns/serve_mux.go:128 +0x5d
github.com/miekg/dns.(*Server).serveDNS(0xc0000b2100, 0xc00027eb00)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:688 +0x2c1
github.com/miekg/dns.(*Server).serve(0xc0000b2100, 0xc00027eb00)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:573 +0x2d8
github.com/miekg/dns.(*Server).worker(0xc0000b2100, 0xc00008e380)
        /home/travis/gopath/src/github.com/miekg/dns/server.go:269 +0x1c2
created by github.com/miekg/dns.(*Server).spawnWorker
        /home/travis/gopath/src/github.com/miekg/dns/server.go:284 +0x86

1.5-rc2 有一样的问题。

**Comment by rampageX** [comment]
1.5-rc2, 几分钟就奔溃了：

```
WARN[0552] DeadWood Fail: read udp 127.0.0.1:3792->127.0.0.1:5050: i/o timeout
WARN[0552] DNSPOD-HTTP Fail: read udp 127.0.0.1:9286->127.0.0.1:5151: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x18f104]

goroutine 532 [running]:
github.com/miekg/dns.(*Msg).PackBuffer(0x0, 0x0, 0x0, 0x0, 0x4, 0x3, 0xc145d0, 0xb92e80, 0x1f4410)
	/home/travis/gopath/src/github.com/miekg/dns/msg.go:757 +0x14
github.com/miekg/dns.(*Msg).Pack(0x0, 0x4, 0x4, 0xc98150, 0x9, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/msg.go:750 +0x30
github.com/miekg/dns.(*response).WriteMsg(0x856180, 0x0, 0x1, 0x80c438)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:770 +0x38
github.com/shawn1m/overture/core/inbound.(*Server).ServeDNS(0x810240, 0x2999f8, 0x856180, 0x87a140)
	/home/travis/gopath/src/github.com/shawn1m/overture/core/inbound/server.go:65 +0x1cc
github.com/miekg/dns.(*ServeMux).ServeDNS(0xadbc20, 0x2999f8, 0x856180, 0x87a140)
	/home/travis/gopath/src/github.com/miekg/dns/serve_mux.go:128 +0x54
github.com/miekg/dns.(*Server).serveDNS(0x8a60a0, 0x856180)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:688 +0x298
github.com/miekg/dns.(*Server).serve(0x8a60a0, 0x856180)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:573 +0x2b0
github.com/miekg/dns.(*Server).worker(0x8a60a0, 0x856180)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:244 +0x24
created by github.com/miekg/dns.(*Server).spawnWorker
	/home/travis/gopath/src/github.com/miekg/dns/server.go:284 +0x64
```

**Comment by shawn1m** [comment]
Try v1.5-rc3.

**Comment by rampageX** [comment]
v1.5-rc3 运行 3 天了没啥问题。
