### ISSUE TITLE
请教build.py文件怎么使用?

### ISSUE THREAD

**Issue by blog2i2j** [shawn1m/overture#274]
我想自己编译一下overture(环境win10), 我看有一个build.py文件, 我用python 3.10无法运行下去, 报错如下. 请教大侠们, 这个build.py是怎么用的? 谢谢

e:\overture-master>C:\python3\python310\python.exe .\build.py -build
'GOOS' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "e:\overture-master\build.py", line 80, in <module>
    go_build_zip(GO_OS_ARCH_LIST, go_build_desktop)
  File "e:\overture-master\build.py", line 39, in go_build_zip
    subprocess.check_call("GOOS=windows go get -v github.com/shawn1m/overture/main", shell=True)
  File "C:\python3\python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'GOOS=windows go get -v github.com/shawn1m/overture/main' returned non-zero exit status 1.

**Comment by blog2i2j** [comment]
已经搞明白了, 这个build.py是macos下的, 我是win, 谢谢. 关闭了
