### ISSUE TITLE
1.3.5-rc4 ARM 版本运行一会就会退出

### ISSUE THREAD

**Issue by rampageX** [shawn1m/overture#48]
软件版本：
下载的 1.3.5-rc4 或者在路由器上本地编译的版本：
go get -v -u github.com/shawn1m/overture/main

运行环境：
ASUS RT-AC68U / Tomato
Buffalo WZR-1750DHP / DD-WRT

问题：
运行一会程序就会退出，换回 rc3 则无问题

调试信息:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1e6100]

goroutine 139 [running]:
github.com/shawn1m/overture/core/cache.(*Cache).InsertMessage(0x1076bd00, 0x10889e60, 0x15, 0x0)
	/mnt/sda2/compile/go/src/github.com/shawn1m/overture/core/cache/cache.go:74 +0x34
github.com/shawn1m/overture/core/outbound.(*ClientBundle).CacheResults(0x10898090)
	/mnt/sda2/compile/go/src/github.com/shawn1m/overture/core/outbound/clientbundle.go:97 +0xa4
github.com/shawn1m/overture/core/outbound.(*Dispatcher).Exchange(0x1064e680)
	/mnt/sda2/compile/go/src/github.com/shawn1m/overture/core/outbound/dispatcher.go:42 +0xac
github.com/shawn1m/overture/core/inbound.(*Server).ServeDNS(0x10658540, 0x333950, 0x1087ef00, 0x1088a780)
	/mnt/sda2/compile/go/src/github.com/shawn1m/overture/core/inbound/server.go:65 +0x1c4
github.com/miekg/dns.(*ServeMux).ServeDNS(0x10650538, 0x333950, 0x1087ef00, 0x1088a780)
	/mnt/sda2/compile/go/src/github.com/miekg/dns/server.go:210 +0x4c
github.com/miekg/dns.(*Server).serve(0x10652360, 0x331798, 0x10889340, 0x3309b0, 0x10650538, 0x10890000, 0x21, 0x200, 0x10650598, 0x10845da0, ...)
	/mnt/sda2/compile/go/src/github.com/miekg/dns/server.go:579 +0x240
created by github.com/miekg/dns.(*Server).serveUDP
	/mnt/sda2/compile/go/src/github.com/miekg/dns/server.go:533 +0x218
```

**Comment by shawn1m** [comment]
Fixed by @V-E-O , try 1.3.5-rc5.

**Comment by rampageX** [comment]
Thx @shawn1m @V-E-O , RC5 it's worked~
